In [24]:
import datetime
import time
from collections import defaultdict
import pandas as pd
from time import mktime

import yfinance as yf
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
import numpy

stock_tickers = [
    'AMZN',
    'GOOGL',
    'MSFT',
    'ROKU',
    'NVDA',
    'CROX'
]

string_formatted_ticker_list = " ".join(stock_tickers)

data = yf.download(['SPY', 'AMZN', 'GOOGL', 'MSFT', 'NVDA', 'PYPL', 'HUBS', 'CROX', 'NKE', 'ADBE', 'BLK', 'TWTR', 'QCOM', 'FB',
                   'TGT', 'AAPL', 'EBAY', 'CRWD', 'CLF', 'NFLX', 'LB', 'LEVI', 'STLD', 'NET', 'VUG', 'INTU', 'SBUX', 'AZN', 'ASAN', 'MS','CMG',
                   'IT', 'MCO'], start="2021-01-01", end="2021-07-13")
df = data['Close']
df

[*********************100%***********************]  33 of 33 completed

,AAPL,ADBE,AMZN,ASAN,AZN,BLK,CLF,CMG,CROX,CRWD,...,NKE,NVDA,PYPL,QCOM,SBUX,SPY,STLD,TGT,TWTR,VUG
Date,,,,,,,,,,,,,,,,,,,,,
2021-01-04,129.410004,485.339996,3186.629883,29.000000,50.520000,710.820007,14.420000,1319.119995,61.560001,200.490005,...,140.100006,524.539978,231.919998,148.500000,103.099998,368.790009,36.619999,177.630005,54.529999,249.660004
2021-01-05,131.009995,485.690002,3218.510010,28.549999,50.700001,714.580017,15.700000,1355.109985,64.209999,211.240005,...,141.229996,536.190002,234.910004,152.429993,103.440002,371.329987,37.950001,180.369995,53.880001,251.279999
2021-01-06,126.599998,466.309998,3138.379883,28.030001,50.910000,734.960022,17.420000,1343.410034,67.620003,208.850006,...,142.350006,504.579987,226.830002,151.190002,104.190002,373.549988,40.630001,188.919998,53.259998,248.529999
2021-01-07,130.919998,477.739990,3162.159912,28.900000,50.189999,750.419983,17.670000,1368.140015,67.180000,221.470001,...,144.949997,533.760010,235.039993,155.699997,103.349998,379.100006,39.849998,191.100006,52.330002,254.270004
2021-01-08,132.050003,485.100006,3182.699951,31.580000,50.860001,756.450012,18.040001,1402.439941,66.779999,223.729996,...,146.350006,531.070007,242.460007,156.639999,105.669998,381.260010,39.490002,193.600006,51.480000,256.989990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-07-06,142.020004,596.900024,3675.739990,68.510002,59.900002,892.679993,21.040001,1566.410034,113.629997,264.980011,...,160.110001,827.940002,292.640015,141.190002,115.730003,432.929993,58.220001,245.449997,70.209999,292.329987
2021-07-07,144.570007,605.770020,3696.580078,66.879997,59.759998,900.940002,21.389999,1583.989990,112.809998,267.519989,...,160.160004,814.869995,297.130005,139.970001,117.139999,434.459991,61.220001,247.550003,68.760002,292.890015
2021-07-08,143.240005,605.950012,3731.409912,66.389999,59.259998,876.500000,20.940001,1576.050049,113.449997,263.390015,...,160.630005,796.109985,295.049988,138.289993,115.989998,430.920013,59.959999,248.580002,66.830002,290.790009
2021-07-09,145.110001,604.500000,3719.340088,68.110001,59.630001,901.309998,22.559999,1592.250000,117.000000,264.440002,...,161.000000,802.010010,300.209991,141.429993,117.470001,435.519989,61.500000,248.580002,68.970001,293.059998
2021-07-12,144.500000,600.200012,3718.550049,66.940002,60.500000,915.919983,23.080000,1615.560059,117.610001,261.790009,...,161.820007,820.500000,302.970001,142.470001,118.459999,437.079987,62.849998,252.240005,69.860001,293.700012

In [25]:
# Calculate expected returns and sample covariance
mu = expected_returns.mean_historical_return(df)
S = risk_models.sample_cov(df)

# Optimize for maximal Sharpe ratio
ef = EfficientFrontier(mu, S)
raw_weights = ef.max_sharpe()
cleaned_weights = ef.clean_weights()
ef.save_weights_to_file("weights.csv")  # saves to file
print(cleaned_weights)
ef.portfolio_performance(verbose=True)

OrderedDict([('AAPL', 0.0), ('ADBE', 0.0), ('AMZN', 0.0), ('ASAN', 0.27182), ('AZN', 0.0), ('BLK', 0.0), ('CLF', 0.0), ('CMG', 0.0), ('CROX', 0.0), ('CRWD', 0.0), ('EBAY', 0.0), ('FB', 0.07737), ('GOOGL', 0.0), ('HUBS', 0.0), ('INTU', 0.0), ('IT', 0.22818), ('LB', 0.17966), ('LEVI', 0.11916), ('MCO', 0.0), ('MS', 0.0), ('MSFT', 0.0), ('NET', 0.0), ('NFLX', 0.0), ('NKE', 0.0), ('NVDA', 0.0), ('PYPL', 0.0), ('QCOM', 0.0), ('SBUX', 0.0), ('SPY', 0.0), ('STLD', 0.1238), ('TGT', 0.0), ('TWTR', 0.0), ('VUG', 0.0)])
Expected annual return: 233.7%
Annual volatility: 25.2%
Sharpe Ratio: 9.21

(2.336920310504889, 0.25151477547341544, 9.211865609659908)