,GOOG,AAPL,FB,BABA,AMZN,GE,AMD,WMT,BAC,GM,T,UAA,SHLD,XOM,RRC,BBY,MA,PFE,JPM,SBUX
date,,,,,,,,,,,,,,,,,,,,
1989-12-29,NaN,0.117203,NaN,NaN,NaN,0.352438,3.9375,3.486070,1.752478,NaN,2.365775,NaN,NaN,1.766756,NaN,0.166287,NaN,0.110818,1.827968,NaN
1990-01-02,NaN,0.123853,NaN,NaN,NaN,0.364733,4.1250,3.660858,1.766686,NaN,2.398184,NaN,NaN,1.766756,NaN,0.173216,NaN,0.113209,1.835617,NaN
1990-01-03,NaN,0.124684,NaN,NaN,NaN,0.364050,4.0000,3.660858,1.780897,NaN,2.356516,NaN,NaN,1.749088,NaN,0.194001,NaN,0.113608,1.896803,NaN
1990-01-04,NaN,0.125100,NaN,NaN,NaN,0.362001,3.9375,3.641439,1.743005,NaN,2.403821,NaN,NaN,1.731422,NaN,0.190537,NaN,0.115402,1.904452,NaN
1990-01-05,NaN,0.125516,NaN,NaN,NaN,0.358586,3.8125,3.602595,1.705114,NaN,2.287973,NaN,NaN,1.722587,NaN,0.190537,NaN,0.114405,1.912100,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-04-05,1027.810059,172.800003,159.339996,172.570007,1451.750000,13.430000,10.0200,87.809998,30.320000,38.000000,35.632843,17.469999,2.97,76.019997,14.52,72.120003,175.550003,35.730000,111.879997,59.139999
2018-04-06,1007.039978,168.380005,157.199997,167.520004,1405.229980,13.060000,9.6100,86.690002,29.629999,37.680000,35.130001,16.980000,2.88,74.870003,13.97,70.489998,169.699997,35.169998,109.089996,58.340000
2018-04-09,1015.450012,170.050003,157.929993,169.869995,1406.079956,12.830000,9.5300,86.279999,29.870001,37.830002,35.169998,16.639999,2.82,74.870003,13.93,69.820000,170.339996,35.459999,110.400002,58.700001
2018-04-10,1031.640015,173.250000,165.039993,177.100006,1436.219971,13.050000,9.9800,86.449997,30.480000,39.070000,35.810001,16.820000,3.07,77.070000,14.78,71.720001,174.720001,35.950001,112.510002,59.410000
2018-04-11,1019.969971,172.440002,166.320007,175.360001,1427.050049,12.970000,9.8200,85.910004,29.900000,39.000000,35.250000,16.740000,3.30,77.430000,14.99,70.910004,172.360001,35.790001,110.620003,59.419998

In [2]:
# Calculate expected returns and sample covariance
mu = expected_returns.mean_historical_return(df)
S = risk_models.sample_cov(df)

# Optimize for maximal Sharpe ratio
ef = EfficientFrontier(mu, S)
raw_weights = ef.max_sharpe()
cleaned_weights = ef.clean_weights()
ef.save_weights_to_file("weights.csv")  # saves to file
print(cleaned_weights)
ef.portfolio_performance(verbose=True)

OrderedDict([('GOOG', 0.03835), ('AAPL', 0.0689), ('FB', 0.20603), ('BABA', 0.07315), ('AMZN', 0.04033), ('GE', 0.0), ('AMD', 0.0), ('WMT', 0.0), ('BAC', 0.0), ('GM', 0.0), ('T', 0.0), ('UAA', 0.0), ('SHLD', 0.0), ('XOM', 0.0), ('RRC', 0.0), ('BBY', 0.01324), ('MA', 0.35349), ('PFE', 0.1957), ('JPM', 0.0), ('SBUX', 0.01082)])
Expected annual return: 30.5%
Annual volatility: 22.2%
Sharpe Ratio: 1.28

(0.3047768672819918, 0.22165566922402968, 1.2847714127003216)

In [22]:
import datetime
import time
from collections import defaultdict
import pandas as pd
from time import mktime

import yfinance as yf
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
import numpy

stock_tickers = [
    'AMZN',
    'GOOGL',
    'MSFT',
    'ROKU',
    'NVDA',
    'CROX'
]

string_formatted_ticker_list = " ".join(stock_tickers)

data = yf.download(['SPY', 'AMZN', 'GOOGL', 'MSFT', 'NVDA', 'PYPL', 'HUBS', 'CROX', 'NKE', 'ADBE', 'BLK', 'TWTR', 'QCOM', 'FB',
                   'TGT', 'AAPL', 'EBAY', 'CRWD', 'CLF', 'NFLX', 'LB', 'LEVI', 'STLD', 'NET', 'VUG', 'INTU'], start="2021-01-01", end="2021-07-13")
df = data['Close']
df

[*********************100%***********************]  26 of 26 completed

,AAPL,ADBE,AMZN,BLK,CLF,CROX,CRWD,EBAY,FB,GOOGL,...,NFLX,NKE,NVDA,PYPL,QCOM,SPY,STLD,TGT,TWTR,VUG
Date,,,,,,,,,,,,,,,,,,,,,
2021-01-04,129.410004,485.339996,3186.629883,710.820007,14.420000,61.560001,200.490005,51.500000,268.940002,1726.130005,...,522.859985,140.100006,524.539978,231.919998,148.500000,368.790009,36.619999,177.630005,54.529999,249.660004
2021-01-05,131.009995,485.690002,3218.510010,714.580017,15.700000,64.209999,211.240005,52.029999,270.970001,1740.050049,...,520.799988,141.229996,536.190002,234.910004,152.429993,371.329987,37.950001,180.369995,53.880001,251.279999
2021-01-06,126.599998,466.309998,3138.379883,734.960022,17.420000,67.620003,208.850006,53.220001,263.309998,1722.880005,...,500.489990,142.350006,504.579987,226.830002,151.190002,373.549988,40.630001,188.919998,53.259998,248.529999
2021-01-07,130.919998,477.739990,3162.159912,750.419983,17.670000,67.180000,221.470001,53.060001,268.739990,1774.339966,...,508.890015,144.949997,533.760010,235.039993,155.699997,379.100006,39.849998,191.100006,52.330002,254.270004
2021-01-08,132.050003,485.100006,3182.699951,756.450012,18.040001,66.779999,223.729996,54.480000,267.570007,1797.829956,...,510.399994,146.350006,531.070007,242.460007,156.639999,381.260010,39.490002,193.600006,51.480000,256.989990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-07-06,142.020004,596.900024,3675.739990,892.679993,21.040001,113.629997,264.980011,69.019997,352.779999,2523.800049,...,541.640015,160.110001,827.940002,292.640015,141.190002,432.929993,58.220001,245.449997,70.209999,292.329987
2021-07-07,144.570007,605.770020,3696.580078,900.940002,21.389999,112.809998,267.519989,70.070000,350.489990,2529.479980,...,535.960022,160.160004,814.869995,297.130005,139.970001,434.459991,61.220001,247.550003,68.760002,292.890015
2021-07-08,143.240005,605.950012,3731.409912,876.500000,20.940001,113.449997,263.390015,68.650002,345.649994,2500.879883,...,530.760010,160.630005,796.109985,295.049988,138.289993,430.920013,59.959999,248.580002,66.830002,290.790009
2021-07-09,145.110001,604.500000,3719.340088,901.309998,22.559999,117.000000,264.440002,69.459999,350.420013,2510.370117,...,535.979980,161.000000,802.010010,300.209991,141.429993,435.519989,61.500000,248.580002,68.970001,293.059998
2021-07-12,144.500000,600.200012,3718.550049,915.919983,23.080000,117.610001,261.790009,68.970001,353.160004,2539.510010,...,537.309998,161.820007,820.500000,302.970001,142.470001,437.079987,62.849998,252.240005,69.860001,293.700012

In [23]:
# Calculate expected returns and sample covariance
mu = expected_returns.mean_historical_return(df)
S = risk_models.sample_cov(df)

# Optimize for maximal Sharpe ratio
ef = EfficientFrontier(mu, S)
raw_weights = ef.max_sharpe()
cleaned_weights = ef.clean_weights()
ef.save_weights_to_file("weights.csv")  # saves to file
print(cleaned_weights)
ef.portfolio_performance(verbose=True)

OrderedDict([('AAPL', 0.0), ('ADBE', 0.0), ('AMZN', 0.0), ('BLK', 0.0), ('CLF', 0.0), ('CROX', 0.11244), ('CRWD', 0.0), ('EBAY', 0.0), ('FB', 0.0), ('GOOGL', 0.29671), ('HUBS', 0.0), ('INTU', 0.0), ('LB', 0.19589), ('LEVI', 0.09688), ('MSFT', 0.0), ('NET', 0.0), ('NFLX', 0.0), ('NKE', 0.0), ('NVDA', 0.08126), ('PYPL', 0.0), ('QCOM', 0.0), ('SPY', 0.0), ('STLD', 0.11725), ('TGT', 0.09958), ('TWTR', 0.0), ('VUG', 0.0)])
Expected annual return: 165.1%
Annual volatility: 23.0%
Sharpe Ratio: 7.09

(1.6507820793923778, 0.23014702310401294, 7.085827387197444)